// fzf picker wrapper, with a chafa cover-art preview pane.

import { mkdir, chmod } from "node:fs/promises";
import { join } from "node:path";
import { CACHE_DIR, COVERS_DIR } from "../utils/paths.ts";
import { loadConfig } from "../utils/config.ts";

export interface PickItem {
  /** Display text; may contain ANSI escapes (rendered via fzf --ansi). */
  label: string;
  /** Cover image URL for the preview pane (optional). */
  previewUrl?: string;
}

export interface PickOpts {
  prompt?: string;
  header?: string;
  preview?: boolean;
  extraArgs?: string[];
}

// A pleasant violet/cyan fzf theme to match the banner.
const FZF_COLORS =
  "fg:-1,bg:-1,hl:#a78bfa,fg+:#ffffff,bg+:#262335,hl+:#22d3ee," +
  "info:#6b7280,prompt:#a78bfa,pointer:#22d3ee,marker:#f472b6,spinner:#a78bfa," +
  "header:#6b7280,border:#3b3b54,gutter:-1,label:#a78bfa," +
  "separator:#3b3b54,scrollbar:#3b3b54,preview-border:#3b3b54";

// Preview pane renders covers as chafa symbols (universally safe inside fzf).
const PREVIEW_TEMPLATE = `#!/usr/bin/env bash
# Auto-generated by manga-cli — renders a manga cover in the fzf preview pane.
url="$1"
[ -z "$url" ] && exit 0
dir="__COVERS_DIR__"
mkdir -p "$dir" 2>/dev/null
if command -v md5 >/dev/null 2>&1; then
  h=$(printf '%s' "$url" | md5)
else
  h=$(printf '%s' "$url" | md5sum | cut -d' ' -f1)
fi
f="$dir/$h.img"
if [ ! -f "$f" ]; then
  curl -sL --max-time 10 -A "Mozilla/5.0" -H "Referer: https://atsu.moe/" "$url" -o "$f" 2>/dev/null
fi
cols="\${FZF_PREVIEW_COLUMNS:-40}"
lines="\${FZF_PREVIEW_LINES:-20}"
chafa -f symbols --size "\${cols}x\${lines}" --animate off "$f" 2>/dev/null || echo "  (no preview)"
`;

let previewScriptPath: string | null = null;
async function ensurePreviewScript(): Promise<string> {
  if (previewScriptPath) return previewScriptPath;
  await mkdir(CACHE_DIR, { recursive: true });
  const path = join(CACHE_DIR, "preview.sh");
  await Bun.write(path, PREVIEW_TEMPLATE.replace("__COVERS_DIR__", COVERS_DIR));
  await chmod(path, 0o755);
  previewScriptPath = path;
  return path;
}

function shQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

// Shared fzf invocation. Returns the indices the user selected (0..n) — a single
// element for normal pick, possibly many when `multi` is set.
async function runFzf<T extends PickItem>(
  items: T[],
  opts: PickOpts,
  multi: boolean,
): Promise<number[]> {
  if (items.length === 0) return [];

  const input = items.map((it, i) => `${it.label}\t${i}\t${it.previewUrl ?? ""}`).join("\n");

  const args = [
    "--ansi",
    "--delimiter",
    "\t",
    "--with-nth",
    "1",
    "--height",
    "100%",
    "--layout",
    "reverse",
    "--info",
    "inline-right",
    "--cycle",
    "--no-mouse",
    "--border",
    "rounded",
    "--border-label",
    " 漫画 manga-cli ",
    "--border-label-pos",
    "3",
    "--highlight-line",
    "--ellipsis",
    "…",
    "--scrollbar",
    "▐",
    "--separator",
    "─",
    "--prompt",
    opts.prompt ?? "❯ ",
    "--pointer",
    "▌",
    "--marker",
    "✓",
    "--color",
    FZF_COLORS,
  ];
  if (multi) args.push("--multi", "--bind", "tab:toggle+down,shift-tab:toggle+up");
  if (opts.header) args.push("--header", opts.header);
  if (opts.preview) {
    const script = await ensurePreviewScript();
    args.push("--preview", `${shQuote(script)} {3}`, "--preview-window", "right,45%,border-left");
  }
  if (opts.extraArgs) args.push(...opts.extraArgs);

  // User-configured extra fzf args (naive whitespace split).
  const cfg = await loadConfig();
  if (cfg.fzfArgs.trim()) args.push(...cfg.fzfArgs.trim().split(/\s+/));

  const proc = Bun.spawn(["fzf", ...args], { stdin: "pipe", stdout: "pipe", stderr: "inherit" });
  proc.stdin.write(input);
  proc.stdin.end();
  const out = (await new Response(proc.stdout).text()).trim();
  await proc.exited;

  if (!out) return []; // Esc / Ctrl-C / no match
  const indices: number[] = [];
  for (const line of out.split("\n")) {
    const idx = Number(line.split("\t")[1]);
    if (Number.isInteger(idx) && idx >= 0 && idx < items.length) indices.push(idx);
  }
  return indices;
}

/**
 * Present `items` in fzf and return the chosen one (or null if cancelled).
 * Each line is `label \t index \t previewUrl`; only the label is shown/searched.
 */
export async function fzfPick<T extends PickItem>(
  items: T[],
  opts: PickOpts = {},
): Promise<T | null> {
  const [idx] = await runFzf(items, opts, false);
  return idx === undefined ? null : items[idx] ?? null;
}

/** Multi-select variant (Tab to toggle). Returns the selected items in list order. */
export async function fzfPickMulti<T extends PickItem>(
  items: T[],
  opts: PickOpts = {},
): Promise<T[]> {
  const indices = await runFzf(items, opts, true);
  return indices.map((i) => items[i]).filter((x): x is T => x !== undefined);
}
