// fzf picker wrapper, with a chafa cover-art preview pane.

import { mkdir, chmod } from "node:fs/promises";
import { join } from "node:path";
import { CACHE_DIR, COVERS_DIR } from "../utils/paths.ts";
import { loadConfig } from "../utils/config.ts";

export interface PickItem {
  /** Display text; may contain ANSI escapes (rendered via fzf --ansi). */
  label: string;
  /** Cover image URL for the preview pane (optional). */
  previewUrl?: string;
}

export interface PickOpts {
  prompt?: string;
  header?: string;
  preview?: boolean;
  extraArgs?: string[];
}

// A pleasant violet/cyan fzf theme to match the banner.
const FZF_COLORS =
  "fg:-1,bg:-1,hl:#a78bfa,fg+:#ffffff,bg+:#262335,hl+:#22d3ee," +
  "info:#6b7280,prompt:#a78bfa,pointer:#22d3ee,marker:#f472b6,spinner:#a78bfa," +
  "header:#6b7280,border:#3b3b54,gutter:-1";

// Preview pane renders covers as chafa symbols (universally safe inside fzf).
const PREVIEW_TEMPLATE = `#!/usr/bin/env bash
# Auto-generated by manga-cli — renders a manga cover in the fzf preview pane.
url="$1"
[ -z "$url" ] && exit 0
dir="__COVERS_DIR__"
mkdir -p "$dir" 2>/dev/null
if command -v md5 >/dev/null 2>&1; then
  h=$(printf '%s' "$url" | md5)
else
  h=$(printf '%s' "$url" | md5sum | cut -d' ' -f1)
fi
f="$dir/$h.img"
if [ ! -f "$f" ]; then
  curl -sL --max-time 10 -A "Mozilla/5.0" -H "Referer: https://atsu.moe/" "$url" -o "$f" 2>/dev/null
fi
cols="\${FZF_PREVIEW_COLUMNS:-40}"
lines="\${FZF_PREVIEW_LINES:-20}"
chafa -f symbols --size "\${cols}x\${lines}" --animate off "$f" 2>/dev/null || echo "  (no preview)"
`;

let previewScriptPath: string | null = null;
async function ensurePreviewScript(): Promise<string> {
  if (previewScriptPath) return previewScriptPath;
  await mkdir(CACHE_DIR, { recursive: true });
  const path = join(CACHE_DIR, "preview.sh");
  await Bun.write(path, PREVIEW_TEMPLATE.replace("__COVERS_DIR__", COVERS_DIR));
  await chmod(path, 0o755);
  previewScriptPath = path;
  return path;
}

function shQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * Present `items` in fzf and return the chosen one (or null if cancelled).
 * Each line is `label \t index \t previewUrl`; only the label is shown/searched.
 */
export async function fzfPick<T extends PickItem>(
  items: T[],
  opts: PickOpts = {},
): Promise<T | null> {
  if (items.length === 0) return null;

  const input = items
    .map((it, i) => `${it.label}\t${i}\t${it.previewUrl ?? ""}`)
    .join("\n");

  const args = [
    "--ansi",
    "--delimiter",
    "\t",
    "--with-nth",
    "1",
    "--height",
    "100%",
    "--layout",
    "reverse",
    "--info",
    "inline",
    "--cycle",
    "--no-mouse",
    "--prompt",
    opts.prompt ?? "❯ ",
    "--pointer",
    "▶",
    "--marker",
    "✓",
    "--color",
    FZF_COLORS,
  ];
  if (opts.header) args.push("--header", opts.header);
  if (opts.preview) {
    const script = await ensurePreviewScript();
    args.push("--preview", `${shQuote(script)} {3}`, "--preview-window", "right,45%,border-left");
  }
  if (opts.extraArgs) args.push(...opts.extraArgs);

  // User-configured extra fzf args (naive whitespace split).
  const cfg = await loadConfig();
  if (cfg.fzfArgs.trim()) args.push(...cfg.fzfArgs.trim().split(/\s+/));

  const proc = Bun.spawn(["fzf", ...args], {
    stdin: "pipe",
    stdout: "pipe",
    stderr: "inherit",
  });
  proc.stdin.write(input);
  proc.stdin.end();
  const out = (await new Response(proc.stdout).text()).trim();
  await proc.exited;

  if (!out) return null; // Esc / Ctrl-C / no match
  const idx = Number(out.split("\t")[1]);
  if (!Number.isInteger(idx) || idx < 0 || idx >= items.length) return null;
  return items[idx] ?? null;
}
